default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_development

staging:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_staging

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_production